package com.craftsmanbro.fulcraft.infrastructure.llm.impl.provider;

import com.craftsmanbro.fulcraft.config.Config;
import com.craftsmanbro.fulcraft.infrastructure.llm.contract.LlmClientPort;
import com.craftsmanbro.fulcraft.infrastructure.llm.model.Capability;
import com.craftsmanbro.fulcraft.infrastructure.llm.model.ProviderProfile;
import java.util.regex.Pattern;

/**
 * A mock implementation of {@link LlmClientPort} for testing purposes. Generates a dummy unit test
 * implementation based on the input prompt.
 */
public class MockLlmClient implements LlmClientPort {

  private static final String DEFAULT_MODEL_TAG = "mock";

  private static final String DEFAULT_CLASS_NAME = "GeneratedTest";

  private static final Pattern PACKAGE_PATTERN = Pattern.compile("package\\s+([a-zA-Z_][\\w\\.]+)");

  private static final Pattern CLASS_PATTERN = Pattern.compile("class\\s+([A-Za-z_]\\w*)");

  private static final Pattern TEST_NAME_HINT_PATTERN =
      Pattern.compile(
          "test\\s+class\\s+name\\s*(?:must\\s+be\\s+exactly\\s*)?[:=]\\s*([a-z_]\\w*)",
          Pattern.CASE_INSENSITIVE);

  /**
   * Generates a mock unit test class string.
   *
   * @param prompt The prompt containing the source code or hints.
   * @param llmConfig Configuration for the LLM (used to determine model tag).
   * @return The generated Java source code for the test class.
   */
  @Override
  public String generateTest(final String prompt, final Config.LlmConfig llmConfig) {
    final var packageName = extractPackage(prompt);
    final var className = extractClassName(prompt);
    final var modelTag = determineModelTag(llmConfig);
    final var packageDeclaration = packageName.isEmpty() ? "" : "package " + packageName + ";\n\n";
    return """
            %simport org.junit.jupiter.api.Test;
            import static org.junit.jupiter.api.Assertions.*;

            public class %s {
                @Test
                void testGenerated() {
                    // Generated by MockLlmClient, model=%s
                    assertTrue(true);
                }
            }
            """
        .formatted(packageDeclaration, className, modelTag);
  }

  private String determineModelTag(final Config.LlmConfig llmConfig) {
    if (llmConfig != null
        && llmConfig.getModelName() != null
        && !llmConfig.getModelName().isBlank()) {
      return llmConfig.getModelName();
    }
    if (llmConfig != null
        && llmConfig.getProvider() != null
        && !llmConfig.getProvider().isBlank()) {
      return llmConfig.getProvider();
    }
    return DEFAULT_MODEL_TAG;
  }

  private String extractPackage(final String prompt) {
    if (prompt == null) {
      return "";
    }
    final var packageMatcher = PACKAGE_PATTERN.matcher(prompt);
    if (packageMatcher.find()) {
      return packageMatcher.group(1);
    }
    return "";
  }

  private String extractClassName(final String prompt) {
    if (prompt == null) {
      return DEFAULT_CLASS_NAME;
    }
    final var testNameMatcher = TEST_NAME_HINT_PATTERN.matcher(prompt);
    if (testNameMatcher.find()) {
      return testNameMatcher.group(1);
    }
    final var explicitMatcher = CLASS_PATTERN.matcher(prompt);
    if (explicitMatcher.find()) {
      return explicitMatcher.group(1);
    }
    final var hashSuffix = Integer.toHexString(prompt.hashCode());
    return DEFAULT_CLASS_NAME + "_" + hashSuffix;
  }

  @Override
  public ProviderProfile profile() {
    return new ProviderProfile(
        DEFAULT_MODEL_TAG, java.util.Set.of(Capability.SEED), java.util.Optional.empty());
  }
}
