/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

import org.gradle.plugins.signing.Sign

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.diffplug.spotless") version "6.25.0"
    id("checkstyle")
    id("com.github.spotbugs") version "6.0.18"
    id("pmd")
    id("jacoco")
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("org.owasp.dependencycheck") version "9.2.0"
    id("eclipse")
    signing
}

jacoco {
    toolVersion = "0.8.10"
}

configure<com.diffplug.gradle.spotless.SpotlessExtension> {
    java {
        target("src/*/java/**/*.java")
        googleJavaFormat()
    }
}

checkstyle {
    toolVersion = "10.12.1"
    configDirectory.set(rootProject.layout.projectDirectory.dir("config/checkstyle"))
}

val staticAnalysisFailOnViolation = providers
    .gradleProperty("staticAnalysis.failOnViolation")
    .map { it.toBoolean() }
    .orElse(false)

tasks.withType<Checkstyle> {
    ignoreFailures = !staticAnalysisFailOnViolation.get()
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}

spotbugs {
    toolVersion.set("4.8.3")
    effort.set(com.github.spotbugs.snom.Effort.MAX)
    reportLevel.set(com.github.spotbugs.snom.Confidence.LOW)
    excludeFilter.set(rootProject.layout.projectDirectory.file("config/spotbugs/excludeFilter.xml"))
}

tasks.withType<com.github.spotbugs.snom.SpotBugsTask> {
    ignoreFailures = !staticAnalysisFailOnViolation.get()
    reports {
        val htmlReport = maybeCreate("html")
        htmlReport.required.set(true)
        val xmlReport = maybeCreate("xml")
        xmlReport.required.set(true)
    }
}

pmd {
    toolVersion = "7.10.0"
    ruleSetFiles = files(rootProject.layout.projectDirectory.file("config/pmd/ruleset.xml"))
    ruleSets = emptyList()
}

tasks.withType<Pmd> {
    // Keep production and test rules separated to avoid over-enforcing style on tests.
    val mainRules = rootProject.layout.projectDirectory.file("config/pmd/ruleset.xml")
    val testRules = rootProject.layout.projectDirectory.file("config/pmd/ruleset-test.xml")
    ruleSetFiles = if (name == "pmdMain") files(mainRules) else files(testRules)
    if (name != "pmdMain") {
        // Keep non-main PMD analysis source-focused to avoid noisy type-resolution failures.
        classpath = files()
    }

    ignoreFailures = !staticAnalysisFailOnViolation.get()
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.assertj.core)
    testImplementation("com.tngtech.archunit:archunit:1.4.1")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.12.0")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation("org.mockito:mockito-core:5.22.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.22.0")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.javaparser.core)
    implementation(libs.javaparser.symbol.solver.core)
    implementation(libs.jackson.databind)
    implementation(libs.jackson.dataformat.yaml)
    implementation(libs.picocli)
    implementation(libs.snakeyaml)
    implementation(libs.spoon.core)
    implementation(libs.slf4j.api)
    implementation(libs.logback.classic)
    implementation(libs.opentelemetry.api)
    implementation(libs.opentelemetry.sdk)
    implementation(libs.opentelemetry.exporter.logging)
    implementation(libs.commons.lang3)
    implementation(libs.commons.text)
    implementation(libs.resilience4j.retry)
    implementation(libs.resilience4j.circuitbreaker)
    implementation(libs.resilience4j.ratelimiter)
    implementation(libs.h2.mvstore)
    implementation(libs.smallrye.config)
    implementation(libs.json.schema.validator)
    // Lanterna for TUI support
    implementation("com.googlecode.lanterna:lanterna:3.1.1")
    compileOnly("com.github.spotbugs:spotbugs-annotations:4.8.3")
    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

eclipse {
    classpath {
        file {
            whenMerged {
                val classpath = this as org.gradle.plugins.ide.eclipse.model.Classpath
                classpath.entries.forEach { entry ->
                    if (entry is org.gradle.plugins.ide.eclipse.model.SourceFolder) {
                        if (entry.path.contains("src/test/") || entry.path.contains("src/integrationTest/") || entry.path.contains("src/e2eTest/")) {
                            entry.entryAttributes["ignore_optional_problems"] = "true"
                        }
                    }
                }
            }
        }
    }
}

tasks.withType<JavaCompile>().configureEach {
    if (name.lowercase().contains("test")) {
        options.compilerArgs.addAll(listOf("-Xlint:none", "-nowarn"))
    }
}


application {
    // Define the main class for the application.
    mainClass.set("com.craftsmanbro.fulcraft.Main")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    finalizedBy(tasks.jacocoTestReport)
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
    classDirectories.setFrom(
        files(classDirectories.files.map {
            fileTree(it) {
                exclude("**/generated/**", "**/templates/**")
            }
        })
    )
}

// --- Source Sets for Integration and E2E Tests ---

sourceSets {
    create("integrationTest") {
        compileClasspath += sourceSets.main.get().output + sourceSets.test.get().output
        runtimeClasspath += sourceSets.main.get().output + sourceSets.test.get().output
    }
    create("e2eTest") {
        compileClasspath += sourceSets.main.get().output + sourceSets.test.get().output
        runtimeClasspath += sourceSets.main.get().output + sourceSets.test.get().output
    }
}

// Make testImplementation dependencies available to new source sets
val integrationTestImplementation by configurations.getting {
    extendsFrom(configurations.testImplementation.get())
}
val e2eTestImplementation by configurations.getting {
    extendsFrom(configurations.testImplementation.get())
}

// --- Tasks for Integration and E2E Tests ---

val integrationTest = tasks.register<Test>("integrationTest") {
    description = "Runs integration tests."
    group = "verification"

    testClassesDirs = sourceSets["integrationTest"].output.classesDirs
    classpath = sourceSets["integrationTest"].runtimeClasspath
    useJUnitPlatform()

    shouldRunAfter("test")
}

val e2eTest = tasks.register<Test>("e2eTest") {
    description = "Runs end-to-end tests."
    group = "verification"

    testClassesDirs = sourceSets["e2eTest"].output.classesDirs
    classpath = sourceSets["e2eTest"].runtimeClasspath
    useJUnitPlatform()

    // Only run if explicitly requested or specific env var is set
    // This prevents accidental execution of expensive/external tests
    onlyIf {
        System.getenv("RUN_E2E") == "true" || project.hasProperty("e2e")
    }

    shouldRunAfter("integrationTest")
}


tasks.named("check") {
    dependsOn(integrationTest)
}

tasks.named<Delete>("clean") {
    delete("logs", "bin", "target", "out")
    delete(fileTree(".").matching {
        include("*.json", "*.jsonl")
    })
}

// Get version from version catalog
val fulVersion = providers.gradleProperty("fulVersion").orNull
    ?: libs.versions.ful.get()

// Generate version.properties for runtime version detection
tasks.register("generateVersionProperties") {
    val outputDir = layout.buildDirectory.dir("resources/main")
    outputs.dir(outputDir)
    
    doLast {
        val propsFile = outputDir.get().asFile.resolve("version.properties")
        propsFile.parentFile.mkdirs()
        propsFile.writeText("""
            version=$fulVersion
            build.timestamp=${System.currentTimeMillis()}
        """.trimIndent())
        println("Generated version.properties with version: $fulVersion")
    }
}

tasks.named("processResources") {
    dependsOn("generateVersionProperties")
}

tasks.shadowJar {
    archiveBaseName.set("ful")
    archiveClassifier.set("")
    archiveVersion.set(fulVersion)
    manifest {
        attributes["Main-Class"] = "com.craftsmanbro.fulcraft.Main"
    }
    // Merge service files for SPI (e.g., SLF4J, OpenTelemetry)
    mergeServiceFiles()
}

// Custom distribution ZIP task for easy distribution without Gradle
// Note: The 'application' plugin provides its own 'distZip' task, so we use a different name
tasks.register<Zip>("packageDist") {
    dependsOn(tasks.shadowJar)
    
    group = "distribution"
    description = "Creates a standalone distribution ZIP containing the fat JAR and startup scripts"
    
    val distBaseName = "ful"
    archiveBaseName.set(distBaseName)
    archiveVersion.set(fulVersion)
    destinationDirectory.set(layout.buildDirectory.dir("distributions"))
    
    // Create a top-level directory in the ZIP
    val topDir = "$distBaseName-$fulVersion"
    
    // Include the shadow JAR
    from(tasks.shadowJar.flatMap { it.archiveFile }) {
        into(topDir)
    }
    
    // Include startup scripts
    from("${rootProject.projectDir}/scripts/dist") {
        include("ful", "ful.bat", "README.md")
        into(topDir)
        // Set executable permission for Unix script
        filesMatching("ful") {
            mode = 0b111101101 // 0755 in octal
        }
    }
    
    // Include config example
    from("${rootProject.projectDir}/config.example.json") {
        into(topDir)
    }
    
    // Include LICENSE
    from("${rootProject.projectDir}/LICENSE") {
        into(topDir)
    }
    
    // Include NOTICE if it exists
    from("${rootProject.projectDir}") {
        include("NOTICE")
        into(topDir)
    }
    
    doLast {
        println("Distribution ZIP created: ${archiveFile.get().asFile.absolutePath}")
    }
}

// Alias for convenience: ./gradlew distZip will build the custom package
tasks.named("distZip") {
    dependsOn("packageDist")
}

// Generate SHA256 checksum files for distribution artifacts
tasks.register("distChecksum") {
    dependsOn("packageDist", "signReleaseArtifacts")
    
    group = "distribution"
    description = "Generates SHA256 checksum files for distribution artifacts"
    
    val packageDistTask = tasks.named<Zip>("packageDist")
    val shadowJarTask = tasks.shadowJar
    
    // Declare inputs for up-to-date checking
    inputs.files(packageDistTask.map { it.archiveFile })
    inputs.files(shadowJarTask.map { it.archiveFile })
    
    // Declare outputs
    val distDir = layout.buildDirectory.dir("distributions")
    outputs.dir(distDir)
    
    doLast {
        @Suppress("PLATFORM_CLASS_MAPPED_TO_KOTLIN")
        fun generateChecksum(file: File): String {
            val md = (Class.forName("java.security.MessageDigest")
                .getMethod("getInstance", String::class.java)
                .invoke(null, "SHA-256")) as java.security.MessageDigest
            val bytes = file.readBytes()
            val hash = md.digest(bytes)
            return hash.fold("") { acc, b -> acc + "%02x".format(b) }
        }
        
        fun writeChecksumFile(targetFile: File) {
            if (!targetFile.exists()) {
                println("Warning: Target file does not exist: ${targetFile.absolutePath}")
                return
            }
            
            val checksum = generateChecksum(targetFile)
            val checksumFile = File(targetFile.absolutePath + ".sha256")
            // Format: SHA256SUM  filename (two spaces, filename only - not path)
            checksumFile.writeText("$checksum  ${targetFile.name}\n")
            println("Checksum generated: ${checksumFile.absolutePath}")
        }
        
        val distDirFile = distDir.get().asFile
        
        // Generate checksum for ZIP
        val zipFile = packageDistTask.get().archiveFile.get().asFile
        writeChecksumFile(zipFile)
        
        // Copy shadow JAR to distributions folder and generate checksum
        val jarFile = shadowJarTask.get().archiveFile.get().asFile
        if (jarFile.exists()) {
            val destJarFile = File(distDirFile, jarFile.name)
            jarFile.copyTo(destJarFile, overwrite = true)
            println("JAR copied: ${destJarFile.absolutePath}")
            writeChecksumFile(destJarFile)
        }

        fun copySignatureFile(targetFile: File) {
            val signatureFile = File(targetFile.absolutePath + ".asc")
            if (!signatureFile.exists()) {
                println("Warning: Signature file does not exist: ${signatureFile.absolutePath}")
                return
            }
            val destSignatureFile = File(distDirFile, signatureFile.name)
            if (signatureFile.absolutePath == destSignatureFile.absolutePath) {
                return
            }
            signatureFile.copyTo(destSignatureFile, overwrite = true)
            println("Signature copied: ${destSignatureFile.absolutePath}")
        }

        // Copy signatures for ZIP and JAR into the distribution folder
        copySignatureFile(zipFile)
        if (jarFile.exists()) {
            copySignatureFile(jarFile)
        }
        
        println("All release artifacts saved to: ${distDirFile.absolutePath}")
    }
}

dependencyCheck {
    failBuildOnCVSS = 8.0F
    formats = listOf("HTML", "JSON")
    val nvdApiKey = System.getenv("NVD_API_KEY")
    if (!nvdApiKey.isNullOrBlank()) {
        nvd.apiKey = nvdApiKey
    }
}

val inMemorySigningKey =
    providers.environmentVariable("ORG_GRADLE_PROJECT_signingKey").orNull
        ?: providers.environmentVariable("GPG_PRIVATE_KEY").orNull
val inMemorySigningPassphrase =
    providers.environmentVariable("ORG_GRADLE_PROJECT_signingPassword").orNull
        ?: providers.environmentVariable("GPG_PASSPHRASE").orNull
val signingKeyName = providers.environmentVariable("SIGNING_GNUPG_KEY_NAME").orNull
val signingPassphrase = providers.environmentVariable("SIGNING_GNUPG_PASSPHRASE").orNull
val signingEnabled = !inMemorySigningKey.isNullOrBlank() || !signingKeyName.isNullOrBlank()
if (!signingKeyName.isNullOrBlank()) {
    extra["signing.gnupg.keyName"] = signingKeyName
}
if (!signingPassphrase.isNullOrBlank()) {
    extra["signing.gnupg.passphrase"] = signingPassphrase
}

signing {
    if (!inMemorySigningKey.isNullOrBlank()) {
        useInMemoryPgpKeys(inMemorySigningKey, inMemorySigningPassphrase)
    } else {
        useGpgCmd()
    }
    isRequired = signingEnabled
    sign(
        tasks.shadowJar.get(),
        tasks.named<Zip>("packageDist").get()
    )
}

tasks.withType<Sign> {
    onlyIf { signingEnabled }
}

tasks.register("signReleaseArtifacts") {
    dependsOn(tasks.named("signShadowJar"), tasks.named("signPackageDist"))
}
