package com.craftsmanbro.fulcraft.plugins.reporting.model;

import com.craftsmanbro.fulcraft.i18n.MessageSource;
import java.util.Locale;

/**
 * Enumeration of supported report output formats.
 *
 * <p>This enum defines the formats in which reports can be generated by the REPORT phase of the FUL
 * pipeline. Each format has specific use cases and characteristics:
 *
 * <h2>Format Comparison</h2>
 *
 * <table border="1">
 * <tr>
 * <th>Format</th>
 * <th>Use Case</th>
 * <th>Readable By</th>
 * </tr>
 * <tr>
 * <td>MARKDOWN</td>
 * <td>Pull request comments, README updates</td>
 * <td>Humans, GitHub/GitLab</td>
 * </tr>
 * <tr>
 * <td>HTML</td>
 * <td>Rich reports with charts</td>
 * <td>Browsers</td>
 * </tr>
 * <tr>
 * <td>JSON</td>
 * <td>CI/CD integration, tooling</td>
 * <td>Machines</td>
 * </tr>
 * <tr>
 * <td>TEXT</td>
 * <td>Console output, logs</td>
 * <td>Humans, logs</td>
 * </tr>
 * <tr>
 * <td>SARIF</td>
 * <td>Static analysis results</td>
 * <td>GitHub Code Scanning, IDEs</td>
 * </tr>
 * </table>
 *
 * <h2>Usage Example</h2>
 *
 * <pre>{@code
 * Config.OutputConfig output = config.getOutput();
 * ReportFormat format = ReportFormat.fromString(output.getFormat().getReport());
 *
 * switch (format) {
 *     case MARKDOWN -> generateMarkdownReport(data);
 *     case HTML -> generateHtmlReport(data);
 *     case JSON -> generateJsonReport(data);
 *     default -> generateTextReport(data);
 * }
 * }</pre>
 *
 * @see ReportData
 * @see com.craftsmanbro.fulcraft.plugins.reporting.contract.ReportWriterPort
 */
public enum ReportFormat {

  /**
   * Markdown format for human-readable reports.
   *
   * <p>Best suited for:
   *
   * <ul>
   *   <li>Pull request comments and descriptions
   *   <li>README documentation updates
   *   <li>Wiki pages
   *   <li>Email reports (rendered)
   * </ul>
   */
  MARKDOWN("md", "text/markdown"),
  /**
   * HTML format for rich, interactive reports.
   *
   * <p>Best suited for:
   *
   * <ul>
   *   <li>Dashboard displays
   *   <li>Detailed reports with charts and graphs
   *   <li>Archive/audit reports
   *   <li>Email reports (embedded)
   * </ul>
   */
  HTML("html", "text/html"),
  /**
   * JSON format for machine-readable output.
   *
   * <p>Best suited for:
   *
   * <ul>
   *   <li>CI/CD pipeline integration
   *   <li>API responses
   *   <li>Data analysis and aggregation
   *   <li>Tool interoperability
   * </ul>
   */
  JSON("json", "application/json"),
  /**
   * Plain text format for console and log output.
   *
   * <p>Best suited for:
   *
   * <ul>
   *   <li>Console/terminal display
   *   <li>Log file inclusion
   *   <li>Simple reporting needs
   *   <li>Environments without rendering support
   * </ul>
   */
  TEXT("txt", "text/plain"),
  /**
   * SARIF (Static Analysis Results Interchange Format) for static analysis results.
   *
   * <p>Best suited for:
   *
   * <ul>
   *   <li>GitHub Code Scanning integration
   *   <li>IDE integration (VS Code, IntelliJ)
   *   <li>Static analysis tool interoperability
   *   <li>Security vulnerability reporting
   * </ul>
   *
   * @see <a href="https://sarifweb.azurewebsites.net/">SARIF Specification</a>
   */
  SARIF("sarif.json", "application/sarif+json"),
  /**
   * YAML format for configuration-friendly output.
   *
   * <p>Best suited for:
   *
   * <ul>
   *   <li>Human-readable structured data
   *   <li>Configuration file generation
   *   <li>GitOps workflows
   * </ul>
   */
  YAML("yaml", "application/x-yaml");

  private final String fileExtension;

  private final String mimeType;

  ReportFormat(final String fileExtension, final String mimeType) {
    this.fileExtension = fileExtension;
    this.mimeType = mimeType;
  }

  /**
   * Returns the file extension for this format (without leading dot).
   *
   * @return the file extension (e.g., "md", "html", "json")
   */
  public String getFileExtension() {
    return fileExtension;
  }

  /**
   * Returns the MIME type for this format.
   *
   * @return the MIME type (e.g., "text/markdown", "application/json")
   */
  public String getMimeType() {
    return mimeType;
  }

  /**
   * Returns the default filename for this format.
   *
   * @return the default filename (e.g., "report.md", "report.html")
   */
  public String getDefaultFilename() {
    if (this == JSON) {
      return "summary.json";
    }
    return "report." + fileExtension;
  }

  /**
   * Returns whether this format is human-readable.
   *
   * @return true if the format is intended for human consumption
   */
  public boolean isHumanReadable() {
    return this == MARKDOWN || this == HTML || this == TEXT;
  }

  /**
   * Returns whether this format is machine-readable (structured).
   *
   * @return true if the format is designed for machine parsing
   */
  public boolean isMachineReadable() {
    return this == JSON || this == SARIF || this == YAML;
  }

  /**
   * Parses a format string into a {@code ReportFormat}.
   *
   * <p>This method is case-insensitive and supports common aliases:
   *
   * <ul>
   *   <li>"md" → MARKDOWN
   *   <li>"htm" → HTML
   *   <li>"txt" → TEXT
   * </ul>
   *
   * @param format the format string to parse
   * @return the corresponding ReportFormat
   * @throws IllegalArgumentException if the format string is not recognized
   */
  public static ReportFormat fromString(final String format) {
    if (format == null || format.isBlank()) {
      // Default format
      return MARKDOWN;
    }
    final String normalized = format.trim().toLowerCase(Locale.ROOT);
    return switch (normalized) {
      case "markdown", "md" -> MARKDOWN;
      case "html", "htm" -> HTML;
      case "json" -> JSON;
      case "text", "txt", "plain" -> TEXT;
      case "sarif", "sarif.json" -> SARIF;
      case "yaml", "yml" -> YAML;
      default ->
          throw new IllegalArgumentException(
              MessageSource.getMessage("report.error.unknown_report_format", format));
    };
  }

  /**
   * Safely parses a format string, returning a default if not recognized.
   *
   * @param format the format string to parse
   * @param defaultFormat the default format to return if parsing fails
   * @return the corresponding ReportFormat, or defaultFormat if not recognized
   */
  public static ReportFormat fromStringOrDefault(
      final String format, final ReportFormat defaultFormat) {
    try {
      return fromString(format);
    } catch (IllegalArgumentException e) {
      return defaultFormat;
    }
  }
}
